export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_USER_PROFILE = "GET_USER_PROFILE";

//Dashboard
export const GET_DASHBOARD_DETAILS="GET_DASHBOARD_DETAILS";

//Hackathon
export const GET_HACKATHON="GET_HACKATHON";
export const GET_HACKATHONS="GET_HACKATHONS";
export const SET_HACKATHON="SET_HACKATHON";

